allowBuilds:
  '@biomejs/biome': true
  better-sqlite3: true
  electron: true
  esbuild: true
  node-pty: true
onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - electron
  - esbuild
  - node-pty
