// Semantic icon set (design doc 10): Lucide is the single icon family.
// Components import by role name from here, never from lucide-react directly,
// so a package swap or a glyph change stays a one-file edit. Icons inherit
// currentColor; pass aria-hidden when a visible label already names the
// control. Sizes per design doc 10: compact controls 14, status 13-14,
// inline micro controls 12.
import {
  ArrowLeft,
  Bot,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleX,
  Container,
  ExternalLink,
  Eye,
  FastForward,
  File,
  Files,
  Folder,
  FolderOpen,
  FolderPlus,
  Forward,
  GitBranch,
  LoaderCircle,
  type LucideIcon,
  MessageSquare,
  Mic,
  PanelLeft,
  PanelRight,
  Play,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Square,
  SquareKanban,
  SquareTerminal,
  X,
} from 'lucide-react'

export const Icon = {
  agent: Bot,
  back: ArrowLeft,
  chat: MessageSquare,
  check: CircleCheck,
  checkSmall: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  close: X,
  container: Container,
  continue: FastForward,
  dictation: Mic,
  directory: FolderOpen,
  external: ExternalLink,
  fail: CircleX,
  file: File,
  files: Files,
  git: GitBranch,
  handoff: Forward,
  kanban: SquareKanban,
  panelLeft: PanelLeft,
  panelRight: PanelRight,
  plus: Plus,
  preview: Eye,
  projects: Folder,
  projectAdd: FolderPlus,
  retry: RefreshCw,
  resume: Play,
  run: Play,
  running: LoaderCircle,
  search: Search,
  send: Send,
  settings: Settings,
  stop: Square,
  terminal: SquareTerminal,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof Icon
export type { LucideIcon }
