// Stable test ids shared by the shell, navigation and chat workspace.
// Kept out of App.tsx so components never import from App (no import cycle).

export const TEST_ID = {
  appShell: 'app-shell',
  leftNav: 'region-left',
  tabStrip: 'tab-strip',
  tabTerminal: 'tab-terminal',
  tabNewChat: 'tab-new-chat',
  /** Context menu of a file tab (right click / ContextMenu key / Shift+F10). */
  tabContextMenu: 'tab-context-menu',
  tabContextCopyRelative: 'tab-context-copy-relative',
  tabContextCopyAbsolute: 'tab-context-copy-absolute',
  actionRowSlot: 'action-row-slot',
  statusBar: 'status-bar',
  statusProjectName: 'status-project-name',
  statusProjectPath: 'status-project-path',
  statusRuntimes: 'status-runtimes',
  statusRuntimeMore: 'status-runtime-more',
  statusGitBranch: 'status-git-branch',
  statusGitStatus: 'status-git-status',
  statusGitNone: 'status-git-none',
  centerSurface: 'region-center-surface',
  rightRegion: 'region-right',
  bottomRegion: 'region-bottom',
  bottomNewTerminal: 'bottom-new-terminal',
  bottomEmpty: 'bottom-empty',
  bottomTerminalError: 'bottom-terminal-error',
  bottomTerminalRetry: 'bottom-terminal-retry',
  leftResizeHandle: 'resize-handle-left',
  bottomResizeHandle: 'resize-handle-bottom',
  projectList: 'project-list',
  projectsHeader: 'projects-header',
  emptyProjectList: 'project-list-empty',
  addProjectButton: 'add-project-button',
  welcomeSurface: 'welcome-surface',
  actionNotice: 'action-notice',
  newChatButton: 'new-chat-button',
  chatWorkspace: 'chat-workspace',
  chatSurfaceHost: 'chat-surface-host',
  terminalHost: 'terminal-host',
  terminalView: 'terminal-view',
  terminalSpawnError: 'terminal-spawn-error',
  terminalRetry: 'terminal-retry',
  startNewChatState: 'start-new-chat-state',
  startNewChatButton: 'start-new-chat-button',
  projectContextMenu: 'project-context-menu',
  projectFilesPanel: 'project-files-panel',
  filesBackButton: 'files-back-button',
  filesProjectName: 'files-project-name',
  fileTree: 'file-tree',
  fileTreeError: 'file-tree-error',
  filePreviewError: 'file-preview-error',
  filePreviewTooLarge: 'file-preview-too-large',
  filePreviewBinary: 'file-preview-binary',
  filePreviewOpenExternal: 'file-preview-open-external',
  filePreviewMonaco: 'file-preview-monaco',
  /** Right-click menu of the read-only file preview (Copy / Select All). */
  editorContextMenu: 'editor-context-menu',
  editorContextCopy: 'editor-context-copy',
  editorContextSelectAll: 'editor-context-select-all',
  terminalPromptInput: 'terminal-prompt-input',
  terminalPromptSend: 'terminal-prompt-send',
  terminalPromptDictation: 'terminal-prompt-dictation',
  handoffPicker: 'handoff-picker',
  handoffPickerLoading: 'handoff-picker-loading',
  handoffPickerUnconfigured: 'handoff-picker-unconfigured',
  handoffPickerConfigure: 'handoff-picker-configure',
  handoffPickerPlainPaste: 'handoff-picker-plain-paste',
  handoffPickerError: 'handoff-picker-error',
  handoffPickerEmpty: 'handoff-picker-empty',
  handoffPickerList: 'handoff-picker-list',
  handoffPickerEntry: 'handoff-picker-entry',
  /** Left-panel footer: the App Settings opener (bottom of the panel). */
  appSettingsButton: 'app-settings-button',
  settingsConfigSection: 'settings-config-section',
  settingsAutoSend: 'settings-auto-send',
  /** App Settings: Ctrl+Tab chat switching on/off (NEKODE-2). */
  settingsChatSwitch: 'settings-chat-switch',
  settingsHandoffDir: 'settings-handoff-dir',
  settingsHandoffDirBrowse: 'settings-handoff-dir-browse',
  settingsHandoffDirSave: 'settings-handoff-dir-save',
  settingsHandoffDirSaved: 'settings-handoff-dir-saved',
  /** Action form icon picker: preset select and the custom-emoji input. */
  settingsActionIconSelect: 'settings-action-icon-select',
  settingsActionIconEmoji: 'settings-action-icon-emoji',
  /** App Settings: terminal font size select. */
  settingsTerminalFontSize: 'settings-terminal-font-size',
  terminalContextMenu: 'terminal-context-menu',
  terminalContextCopy: 'terminal-context-copy',
  terminalContextPaste: 'terminal-context-paste',
  terminalContextSelectAll: 'terminal-context-select-all',
} as const

/** Test ids that depend on record ids (projects/chats/sessions/paths). */
export const testIdFor = {
  projectRow: (projectId: string): string => `project-row-${projectId}`,
  projectSelect: (projectId: string): string => `project-select-${projectId}`,
  projectToggle: (projectId: string): string => `project-toggle-${projectId}`,
  projectChats: (projectId: string): string => `project-chats-${projectId}`,
  projectFiles: (projectId: string): string => `project-files-${projectId}`,
  removeProject: (projectId: string): string => `remove-project-${projectId}`,
  chatRow: (chatId: string): string => `chat-row-${chatId}`,
  terminalView: (chatId: string): string => `terminal-view-${chatId}`,
  bottomTab: (tabId: string): string => `bottom-tab-${tabId}`,
  bottomTabClose: (tabId: string): string => `bottom-tab-close-${tabId}`,
  bottomTerminal: (tabId: string): string => `bottom-terminal-${tabId}`,
  /** File tree entry row (entry ids carry their '/'-separated relative path). */
  fileEntry: (relativePath: string): string => `file-entry-${relativePath}`,
  /** File tab of the tab strip (ids carry the '/'-separated relative path). */
  tabFile: (relativePath: string): string => `tab-file-${relativePath}`,
  /** Close control of a file tab. */
  tabFileClose: (relativePath: string): string => `tab-close-${relativePath}`,
  /** Main-surface pane of one open file tab (hidden view when inactive). */
  filePreviewPane: (relativePath: string): string => `file-preview-pane-${relativePath}`,
}
